package org.example.Pruebas_Mapas;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;
import java.util.Scanner;

public class Diccionario {

    Scanner entrada = new Scanner(System.in);
    Random random = new Random();
   private HashMap<String,String> diccionario;

    public Diccionario() {
        diccionario = new HashMap<>();
    }

    public void insertarPalabras(){
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
        diccionario.put("agua","water"); diccionario.put("aire","air");
        diccionario.put("amor","love"); diccionario.put("amigo","friend");
        diccionario.put("animal","animal"); diccionario.put("árbol","tree");
        diccionario.put("arena","sand"); diccionario.put("arte","art");
        diccionario.put("ave","bird"); diccionario.put("azúcar","sugar");
        diccionario.put("azul","blue"); diccionario.put("barco","ship");
        diccionario.put("bebé","baby"); diccionario.put("beber","drink");
        diccionario.put("belleza","beauty"); diccionario.put("blanco","white");
        diccionario.put("boca","mouth"); diccionario.put("bosque","forest");
        diccionario.put("brazo","arm"); diccionario.put("brillo","shine");
        diccionario.put("bueno","good"); diccionario.put("cabeza","head");
        diccionario.put("caballo","horse"); diccionario.put("café","coffee");
        diccionario.put("calle","street"); diccionario.put("calor","heat");
        diccionario.put("cama","bed"); diccionario.put("camino","path");
        diccionario.put("campo","field"); diccionario.put("canción","song");
        diccionario.put("cara","face"); diccionario.put("carne","meat");
        diccionario.put("carro","car"); diccionario.put("carta","letter");
        diccionario.put("casa","house"); diccionario.put("cielo","sky");
        diccionario.put("ciudad","city"); diccionario.put("claro","clear");
        diccionario.put("clase","class"); diccionario.put("clima","climate");
        diccionario.put("color","color"); diccionario.put("comer","eat");
        diccionario.put("comida","food"); diccionario.put("compra","purchase");
        diccionario.put("corazón","heart"); diccionario.put("correr","run");
        diccionario.put("cosa","thing"); diccionario.put("costa","coast");
        diccionario.put("crecer","grow"); diccionario.put("cruz","cross");
        diccionario.put("cuerpo","body"); diccionario.put("dato","data");
        diccionario.put("dedo","finger"); diccionario.put("día","day");
        diccionario.put("diente","tooth"); diccionario.put("dinero","money");
        diccionario.put("dolor","pain"); diccionario.put("duda","doubt");
        diccionario.put("dulce","sweet"); diccionario.put("edad","age");
        diccionario.put("edificio","building");
        diccionario.put("ejemplo","example");
        diccionario.put("energía","energy"); diccionario.put("error","error");
        diccionario.put("escuela","school"); diccionario.put("espacio","space");
        diccionario.put("espada","sword"); diccionario.put("esperanza","hope");
        diccionario.put("estrella","star"); diccionario.put("estudio","study");
        diccionario.put("familia","family"); diccionario.put("fecha","date");
        diccionario.put("feliz","happy"); diccionario.put("fiesta","party");
        diccionario.put("flor","flower"); diccionario.put("forma","shape");
        diccionario.put("frío","cold"); diccionario.put("fruta","fruit");
        diccionario.put("fuego","fire"); diccionario.put("fuerza","force");
        diccionario.put("gato","cat"); diccionario.put("gente","people");
        diccionario.put("gol","goal"); diccionario.put("golpe","hit");
        diccionario.put("gracia","grace"); diccionario.put("grande","big");
        diccionario.put("grupo","group"); diccionario.put("guerra","war");
        diccionario.put("guía","guide"); diccionario.put("habilidad","skill");
        diccionario.put("hablar","speak"); diccionario.put("hambre","hunger");
        diccionario.put("hermano","brother"); diccionario.put("hierba","grass");
        diccionario.put("historia","history"); diccionario.put("hombre","man");
        diccionario.put("hora","hour"); diccionario.put("humo","smoke");
        diccionario.put("idea","idea"); diccionario.put("iglesia","church");
    }


    public void nuevoPar(){
        System.out.println("Introduce palabra en castellano");
        String espanol = entrada.nextLine();
        System.out.println("Introduce su traduccion en ingles");
        String ingles = entrada.nextLine();
        diccionario.put(espanol,ingles);
    }

    public String traduce(){
        System.out.println("Pon la palabra que quieras traducir");
        String traduce = entrada.nextLine();
        if (diccionario.containsKey(traduce)){
            return "La traduccion es : " + diccionario.get(traduce);
        }else{
           return  "La palabra no esta en el mapa";
        }
    }

    public String palabraAleatoria(){
        ArrayList<String> vector_diccionario = new ArrayList<>(diccionario.keySet());
         int num = random.nextInt(vector_diccionario.size());
        return vector_diccionario.get(num);
    }

    public char primeraLetraTraduccion(String palabra){
        char letra = getDiccionario().get(palabra).charAt(0);
        return letra;
    }

    public HashMap<String, String> getDiccionario() {
        return diccionario;
    }

    public void setDiccionario(HashMap<String, String> diccionario) {
        this.diccionario = diccionario;
    }

    @Override
    public String toString() {
        return "Diccionario{" +
                "diccionario=" + diccionario +
                '}';
    }
}
